# Generated by Django 5.2.4 on 2025-08-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism_name', models.CharField(max_length=100)),
                ('ncbi_id', models.CharField(max_length=50)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('prediction_score', models.FloatField()),
                ('sequence', models.CharField(max_length=200)),
                ('annotation', models.CharField(max_length=200)),
            ],
        ),
    ]
