# Generated by Django 5.2.8 on 2025-12-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_promotermodel_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotermodel',
            name='annotation',
            field=models.CharField(max_length=3000),
        ),
    ]
