# Generated by Django 5.2.8 on 2025-12-18 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_promotermodel_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_annotation', models.CharField(max_length=100)),
                ('kingdom', models.CharField(max_length=100)),
                ('taxid', models.CharField(max_length=30)),
                ('species_taxid', models.CharField(max_length=30)),
                ('organism_name', models.CharField(max_length=100)),
                ('infraspecific_name', models.CharField(max_length=30)),
                ('asm_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='promotermodel',
            name='assembly_annotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.organism'),
        ),
    ]
