# Generated by Django 5.2.8 on 2025-12-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organism_promotermodel_assembly_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='asm_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organism',
            name='infraspecific_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organism',
            name='species_taxid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organism',
            name='taxid',
            field=models.CharField(max_length=100),
        ),
    ]
