# Generated by Django 5.2.12 on 2026-03-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_organism_asm_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='kingdom',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotermodel',
            name='organism_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
